### ISSUE TITLE
Probleme mit der "Programmierung eines ESP32 für Tesla-BLE-Ladesteuerung"!

### ISSUE THREAD

**Issue by michael181074** [top-gun/Tesla-PV-charging#10]
Ich brauche dringend Hilfe! Ich versuche schon seit Tagen einen ESP32 Dev Kit C V4 von Az Delivery in HA zu integrieren, aber nach dem zweiten Kompilierlauf wird immer abgebrochen und ich kann einfach nicht erkennen woran es liegen könnte.
Nachdem ich gemäß Punkt 4 der Anleitung die Konfigurationszeilen eingefügt, gespeichert und auf Install gedrückt habe, bekomme ich gleich zu Beginn eine Warnung in  gelb, das das IDF Framework nicht recommended sei, der Compiliervorgang läuft dann aber erstmal los, bis dann ein paar kryptische, rote Fehlermeldungen kommen und der Prozess ein paar Zeilen später abgebrochen wird.
Ich weiß leider nicht mehr weiter!

**Comment by top-gun** [comment]
Vermutlich ist das ESPHome Add-On in Version 2025.6.1 aufgespielt. Da haben sich Änderungen ergeben, die auch eine Änderung der ESP-Yaml-Dateien erfordern. 

Von PedroKTFC muss jetzt eine neue Version kommen. Ich habe eine vorläufige Version erstellt, die man derzeit zum Erstellen eines ESP32 benutzen kann. Weil es ein Workaround ist, habe ich die nicht im Guide veröffentlicht, der wird aktualisiert wenn PedroKTFC selbst die Änderungen eingebaut hat.

Diese Version sollte laufen:

```
substitutions:
  # all substitutions for this project
  friendly_name: "Tesla BLE F549C4"
  device_name: "tesla-ble-f549c4"
  device_description: Tesla BLE
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin
  charging_amps_max: "16"

esp32:
  # generic ESP32: board esp32dev, variant esp32, flash: 4MB
  # M5stack AtomS3: board esp32-s3-devkitc-1, variant esp32s3, flash: 8MB
  #
  board: esp32dev  # set as needed for your board, see above
  variant: esp32   # set as needed for your board, see above
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.3.2

api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  source: github://top-gun/esphome-tesla-ble-test@yaml

packages:
  base:  github://top-gun/esphome-tesla-ble-test/packages/base.yml@yaml
  common: github://top-gun/esphome-tesla-ble-test/packages/common.yml@yaml
  project: github://top-gun/esphome-tesla-ble-test/packages/project.yml@yaml
  client: github://top-gun/esphome-tesla-ble-test/packages/client.yml@yaml
  # listener: github://PedroKTFC/esphome-tesla-ble/packages/listener.yml # Uncomment this to scan find your VIN BLE MAC address

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries:
    - https://github.com/PedroKTFC/tesla-ble.git

tesla_ble_vehicle:
  odometer:
    name: "Odometer" # Rename if desired
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  battery_range:
    name: "Range"
    unit_of_measurement: "km"
    filters:
      - multiply: 1.60934 # Convert miles to kms
  update_interval: 2s # Base polling interval, used for VCSEC sensors
  post_wake_poll_time: 300 # How long to poll for data after car awakes (s)
  poll_data_period: 60 # Normal period when polling for data when not asleep (s)
  poll_charging_period: 2 # Period to poll for data when charging (s)
  poll_asleep_period: 60 # Period to poll for data when asleep (s)
  

```
